name: 'Build and Test'
description: 'Builds and tests the project'
inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '16.x'
  fetch-depth:
    description: 'Number of commits to fetch'
    required: false
    default: '1'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Install Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install packages
      shell: bash
      run: npm ci
      
    - name: Build
      shell: bash
      run: npm run build
      
    - name: Test
      shell: bash
      run: npm run test --if-present