name: Build

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
    build:
        permissions:
          contents: read
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Build Test
          uses: int3nse-git/int3nse-git/.github/actions/checkout-build-test
          with:
            node-version: ${{ inputs.node-version }}