name: Build

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: 16.x

jobs:
    build:
        permissions:
          contents: read
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Build Test
          uses: KiraSmith-Dev/KiraSmith-Dev/.github/actions/checkout-build-test@main
          with:
            node-version: ${{ inputs.node-version }}