name: Check and Tag New Versions

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '16.x'
      new-version:
        required: false
        type: string

jobs:
  check-and-tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Build Test # We don't really want to tag a release if the build/test fails
        uses: KiraSmith-Dev/KiraSmith-Dev/.github/actions/checkout-build-test@main
        with:
          node-version: ${{ inputs.node-version }}
          fetch-depth: '0' # Need all history to see the latest tag
        
      - name: Tag version
        uses: KiraSmith-Dev/KiraSmith-Dev/.github/actions/npm-tag-version@main
        with:
          new-version: ${{ inputs.new-version }}